default_install_hook_types: [pre-commit,commit-msg, pre-push]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-merge-conflict # No merge conflict markers
        name: No merge conflict markers
        stages: [commit]
      - id: mixed-line-ending # No mix of \n and \r\n
        name: No mixed line endings (LF and CRLF)
        stages: [commit]
      - id: no-commit-to-branch
        name: Not committing to master
        args: [--branch, master]
        stages: [commit]

  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        stages: [commit]
        types: [python]

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.262
    hooks:
      - id: ruff
        args: [--fix]
        stages: [commit]
        types: [python]

  - repo: local
    hooks:
      - id: mypy-all
        name: MyPy (all)
        pass_filenames: false
        files: lakera_chainguard/
        entry: poetry run mypy .
        stages: [push]
        language: system
      - id: pytest
        name: pytest
        stages: [push]
        language: system
        entry: poetry run pytest
        types: [python]
        pass_filenames: false
        verbose: true
